---
- name: install required software
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - ansible
    - argbash
    - autossh
    - centos-release-scl-rh
    - chromium
    - chromedriver
    - dos2unix
    - elinks
    - emacs    
    - exiv2
    - git
    - gimp
    - gnome-tweak-tool
    - hexchat
    - ImageMagick
    - imapsync
    - inkscape
    - ipmitool
    - java-1.8.0-openjdk
    - keepassx
    - lm_sensors
    - mediainfo
    - NetworkManager-openvpn
    - NetworkManager-openvpn-gnome
    - nmap
    - nmap-ncat
    - ntfsprogs
    - poppler-utils # command line utilities for converting PDF files
    - recordmydesktop
    - smartmontools
    - tigervnc
    - terminator
    - transmission
    - uget
    - upower
    - whois
    - youtube-dl
    # downloaded RPMs (often /opt)
    # - TeamViewer
    # - vagrant
    # downloaded standalones (~/bin)
    # - burp
    # - dropbox (headless - cron @reboot, python script)
    # - leiningen
    # - packer
    # - sp-sc-auth (SopCast client)
    # - tor-browser
    # downloaded from Dropbox
    # - truecrypt
    # @nux-desktop
    # - knock
    # - rdesktop
    # - unrar
    # - vlc
    # - xchm    
    # custom repositories
    # - google-chrome-stable @google-chrome
    # - skype    
    # - slack @slack
    # - VirtualBox-5.1 @virtualbox    
    # other
    # - calibre
    # - glibc-common (this package provides iconv command)
  become: yes
