---

- name: create user account
  user:
    name: '{{ username }}'
  become: true

- name: create common directories
  file:
    group: '{{ username }}'
    owner: '{{ username }}'
    mode: 0775
    path: /home/{{ username }}/{{ item }}
    state: directory
  with_items:
    - bin
    - Git/bitbucket.org
    - Git/github.com
    - rdesktop
  become: true

- name: install software from CentOS repositories
  yum:
    name:
      - dos2unix
      - elinks
      - exiv2
      - gimp
      - git
      - glibc-common  # iconv
      - gnome-tweak-tool
      - ImageMagick
      - inkscape
      - java-1.8.0-openjdk
      - poppler-utils
      - python
      - tigervnc
      - whois
  become: true

- name: install software from EPEL repository
  yum:
    name:
      - aalib
      - adobe-source-code-pro-fonts
      - ansible
      - ansible-lint
      - argbash
      - autossh
      - chromium
      - chromedriver
      - cloc
      - cowsay
      - csv
      - csvcat
      - fortune-mod
      - hexchat
      - imapsync
      - jq
      - keepassx
      - mediainfo
      - NetworkManager-l2tp-gnome
      - NetworkManager-openvpn-gnome
      - ntfsprogs
      - python34
      - recordmydesktop
      - rlwrap
      - terminator
      - transmission
      - uget
      - xls2csv
      - yamllint
      - youtube-dl
  become: true

- name: install software from SCL
  yum:
    name: rh-git29
  become: true

- name: install software from nux-dextop repository
  yum:
    name:
      - rdesktop
      - unrar
      - vlc
      - xchm
  become: true

- name: "install Google Chrome and it's repository"
  yum:
    name: '{{ rpm_url_chrome }}'
  become: true

- name: "install Slack and it's repository"
  yum:
    name: '{{ rpm_url_slack }}'
  become: true

- name: "install Skype and it's repository"
  yum:
    name: '{{ rpm_url_skype }}'
  become: true

- name: "install TeamViewer and it's repository"
  yum:
    name: '{{ rpm_url_teamviewer }}'
  become: true

- name: install custom RPMs
  yum:
    name: '{{ rpm_url_custom }}'
  become: true

- name: install software from pip
  pip:
    name:
      - docker
      - molecule
      - python-vagrant
  become: true

- name: install software from npm
  npm:
    name: castnow
    global: true
  become: true

- name: fetch .bashrc
  get_url:
    dest: /home/{{ username }}/.bashrc
    force: true
    group: '{{ username }}'
    mode: 0664
    owner: '{{ username }}'
    url: '{{ config_url_bashrc }}'
  become: true

- name: fetch .gitconfig
  get_url:
    dest: /home/{{ username }}/.gitconfig
    force: true
    group: '{{ username }}'
    mode: 0664
    owner: '{{ username }}'
    url: '{{ config_url_gitconfig }}'
  become: true

- name: fetch .toprc
  get_url:
    dest: /home/{{ username }}/.toprc
    force: true
    group: '{{ username }}'
    mode: 0664
    owner: '{{ username }}'
    url: '{{ config_url_toprc }}'
  become: true

- name: create directories for Terminator config
  file:
    group: '{{ username }}'
    mode: 0775
    owner: '{{ username }}'
    path: /home/{{ username }}/.config/terminator
    state: directory
  become: true

- name: fetch Terminator config
  get_url:
    dest: /home/{{ username }}/.config/terminator/config
    force: true
    group: '{{ username }}'
    mode: 0664
    owner: '{{ username }}'
    url: '{{ config_url_terminator }}'
  become: true

- name: disable ipmievd
  tags: notest
  service:
    enabled: false
    name: ipmievd
    state: stopped
  become: true

# standalone binary (~/bin)
# - burp
# - leiningen
# - packer
# - tor-browser

# install script
# - truecrypt
# - PIA OpenVPN setup
