---

- name: install software from CentOS repositories
  yum:
    name:
      - dos2unix
      - elinks
      - exiv2
      - gimp
      - gnome-tweak-tool
      - ImageMagick
      - inkscape
      - ipmitool
      - java-1.8.0-openjdk
      - lm_sensors
      - nmap
      - nmap-ncat
      - poppler-utils
      - smartmontools
      - tigervnc
      - upower
      - whois
  become: true

- name: install software from EPEL repository
  yum:
    name:
      - adobe-source-code-pro-fonts
      - ansible
      - ansible-lint
      - argbash
      - autossh
      - chromium
      - chromedriver
      - csv
      - csvcat
      - hexchat
      - imapsync
      - jq
      - keepassx
      - mediainfo
      - NetworkManager-l2tp-gnome
      - NetworkManager-openvpn-gnome
      - ntfsprogs
      - python34
      - recordmydesktop
      - terminator
      - transmission
      - uget
      - xls2csv
      - yamllint
      - youtube-dl
  become: true

- name: install software from SCL
  yum:
    name: rh-git29
  become: true

- name: install software from pip
  pip:
    name:
      - molecule
  become: true

- name: install software from npm
  npm:
    name: castnow
    global: true
  become: true

- name: autostart dropbox daemon on boot
  cron:
    job: /home/shellbro/.dropbox-dist/dropboxd
    name: start dropbox daemon
    special_time: reboot
    user: '{{ autostart_user }}'
  become: true
  when: autostart_apps

- name: autostart GUI apps on login
  copy:
    dest: /home/{{ autostart_user }}/.config/autostart
    group: '{{ autostart_user }}'
    mode: 0664
    owner: '{{ autostart_user }}'
    src: '{{ item }}'
  with_fileglob:
    - autostart/*
  become: true
  when: autostart_apps

# TODO:
# downloaded RPMs (/opt)
# - TeamViewer
# - vagrant
# downloaded standalones (~/bin)
# - burp
# - dropbox (headless daemon, python script for managing daemon)
# - leiningen
# - sp-sc-auth (SopCast client)
# - tor-browser
# downloaded from Dropbox
# - truecrypt
# @nux-desktop
# - rdesktop
# - unrar
# - vlc
# - xchm
# custom repositories
# - google-chrome-stable @google-chrome
# - skype
# - slack @slack
# - VirtualBox-5.1 @virtualbox
# other
# - calibre
# - glibc-common (this package provides iconv command)
