---
- name: Make sure user account exists
  user:
    name: "{{ username }}"
  become: true

- name: Create default directories
  file:
    group: "{{ username }}"
    mode: 0775
    owner: "{{ username }}"
    path: /home/{{ username }}/{{ item }}
    state: directory
  with_items:
    - bin
    - Git/bitbucket.org
    - Git/github.com
    - Git/gitlab.com
    - Playground
    - rdesktop
  become: true

- name: Install software from CentOS repositories
  yum:
    name:
      - dos2unix
      - elinks
      - espeak
      - exiv2
      - gimp
      - git
      - glibc-common  # provides /usr/bin/iconv
      - gnome-tweak-tool
      - gnutls-utils  # provides /usr/bin/certtool
      - ImageMagick
      - inkscape
      - java-1.8.0-openjdk
      - libvirt-devel  # required by vagrant-libvirt
      - podman
      - poppler-utils
      - python2
      - rubygems
      - tigervnc
      - tree
      - virt-manager
      - "@^Virtualization Host"
      - whois
      - wireshark-gnome
      - yum-plugin-changelog
      - yum-plugin-versionlock
  become: true

- name: Install software from EPEL repository
  yum:
    name:
      - aalib
      - adobe-source-code-pro-fonts
      - ansible
      - ansible-lint
      - argbash
      - ascii
      - autossh
      - certbot
      - chromium
      - chromedriver
      - cloc
      - cowsay
      - csv
      - csvcat
      - fortune-mod
      - gparted
      - hexchat
      - imapsync
      - inotify-tools
      - jq
      - keepassx
      - mediainfo
      - NetworkManager-l2tp-gnome
      - NetworkManager-openvpn-gnome
      - NetworkManager-pptp-gnome
      - npm
      - ntfsprogs
      - odt2txt
      - p7zip
      - perl-Image-ExifTool
      - pv
      - pwgen
      - python2-certbot-dns-ovh
      - python34
      - python36
      - python36-chardet
      - recordmydesktop
      - rlwrap
      - terminator
      - transmission
      - uget
      - xls2csv
      - yamllint
      - youtube-dl
  become: true

- name: Install software from SCL
  yum:
    name: rh-git29
  become: true

- name: Install software from nux-dextop repository
  yum:
    name:
      - rdesktop
      - unrar
      - vlc
      - xchm
  become: true

- name: Install RPMs and bundled repositories
  yum:
    name:
      - "{{ rpm_url_chrome }}"
      - "{{ rpm_url_skype }}"
      - "{{ rpm_url_slack }}"
      - "{{ rpm_url_teamviewer }}"
  become: true

- name: Install custom RPMs
  yum:
    name: "{{ rpm_url_custom }}"
  become: true

- name: >-
    Update pip and setuptools to newer versions than in CentOS repository
    (python2)
  pip:
    extra_args: --user --upgrade
    name:
      - pip  # run as python2 -m pip
      - setuptools
  become: true
  become_user: "{{ username }}"

- name: Install software with pip (python2)
  pip:
    extra_args: --user
    name:
      - awscli
      - cookiecutter
      - csvtotable
      - docker-py
      - molecule
      - python-vagrant
  become: true
  become_user: "{{ username }}"

- name: >-
    Update pip and setuptools to newer versions than in CentOS repository
    (python3)
  pip:
    executable: python3
    extra_args: --user --upgrade
    name:
      - pip  # run as python3 -m pip
      - setuptools
  become: true
  become_user: "{{ username }}"

- name: Install software with pip (python3)
  pip:
    executable: python3
    extra_args: --user
    name:
      - tensorflow
  become: true
  become_user: "{{ username }}"

- name: Install software with npm
  npm:
    global: true
    name: castnow
    production: true
  become: true

- name: Install software with gem
  gem:
    name: mustache
  become: true
  become_user: "{{ username }}"

- name: Create directories for Terminator config
  file:
    group: "{{ username }}"
    mode: 0775
    owner: "{{ username }}"
    path: /home/{{ username }}/.config/terminator
    state: directory
  become: true

- name: Download configuration files
  get_url:
    dest: "{{ item.dest }}"
    force: true
    group: "{{ username }}"
    mode: 0664
    owner: "{{ username }}"
    url: "{{ item.url }}"
  with_items:
    - dest: /home/{{ username }}/.bashrc
      url: "{{ config_url_bashrc }}"
    - dest: /home/{{ username }}/.gitconfig
      url: "{{ config_url_gitconfig }}"
    - dest: /home/{{ username }}/.toprc
      url: "{{ config_url_toprc }}"
    - dest: /home/{{ username }}/.config/terminator/config
      url: "{{ config_url_terminator }}"
  become: true

- name: Disable teamviewerd
  tags: notest
  service:
    enabled: false
    name: teamviewerd
    state: stopped
  become: true

# standalone binary (~/bin)
# - burp
# - packer
# - tor-browser

# install script
# - truecrypt
