---

- name: install software from CentOS repositories
  yum:
    name:
      - dos2unix
      - elinks
      - exiv2
      - gimp
      - git
      - glibc-common  # iconv
      - gnome-tweak-tool
      - ImageMagick
      - inkscape
      - java-1.8.0-openjdk
      - poppler-utils
      - python
      - tigervnc
      - whois
  become: true

- name: install software from EPEL repository
  yum:
    name:
      - adobe-source-code-pro-fonts
      - ansible
      - ansible-lint
      - argbash
      - autossh
      - chromium
      - chromedriver
      - cloc
      - csv
      - csvcat
      - hexchat
      - imapsync
      - jq
      - keepassx
      - mediainfo
      - NetworkManager-l2tp-gnome
      - NetworkManager-openvpn-gnome
      - ntfsprogs
      - python34
      - recordmydesktop
      - terminator
      - transmission
      - uget
      - xls2csv
      - yamllint
      - youtube-dl
  become: true

- name: install software from SCL
  yum:
    name: rh-git29
  become: true

- name: install software from nux-dextop repository
  yum:
    name:
      - rdesktop
      - unrar
      - vlc
      - xchm
  become: true

- name: install software from pip
  pip:
    name:
      - docker
      - molecule
      - python-vagrant
  become: true

- name: install software from npm
  npm:
    name: castnow
    global: true
  become: true

- name: "install Google Chrome and it's repository"
  yum:
    name: '{{ rpm_url_chrome }}'
  become: true

- name: "install Slack and it's repository"
  yum:
    name: '{{ rpm_url_slack }}'
  become: true

# TODO:
# downloaded RPMs (/opt)
# - TeamViewer
# - vagrant
# - packer
# downloaded standalones (~/bin)
# - burp
# - calibre
# - leiningen
# - sp-sc-auth (SopCast client)
# - tor-browser
# downloaded from Dropbox
# - truecrypt
# custom repositories
# - skype
# - VirtualBox-5.1 @virtualbox
