---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: ansible-role-workstation
    image: shellbro/centos-molecule
    pre_build_image: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x:
        - ANSIBLE0010
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
