---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-workstation
      rpm_url_chrome: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      autostart_apps: false
