---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-workstation
      username: shellbro
      rpm_url_chrome: https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      rpm_url_slack: https://downloads.slack-edge.com/linux_releases/slack-3.3.3-0.1.fc21.x86_64.rpm
      rpm_url_skype: https://repo.skype.com/latest/skypeforlinux-64.rpm
      custom_rpms:
        - https://download.teamviewer.com/download/linux/teamviewer.x86_64.rpm
        - https://releases.hashicorp.com/vagrant/2.2.2/vagrant_2.2.2_x86_64.rpm
      config_url_bashrc: https://raw.githubusercontent.com/shellbro/dotfiles/master/.bashrc
      config_url_gitconfig: https://raw.githubusercontent.com/shellbro/dotfiles/master/.gitconfig
      config_url_toprc: https://raw.githubusercontent.com/shellbro/dotfiles/master/.toprc
      config_url_terminator: https://raw.githubusercontent.com/shellbro/dotfiles/master/.config/terminator/config

      nux_dextop_rpm_url: http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm
